volumes:
  sanaap_local_postgres_data: {}
  sanaap_local_redis_data: {}
  sanaap_local_minio_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: sanaap_local_django
    container_name: sanaap_local_django
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.docker/.django.env
      - ./.envs/.docker/.postgres.env
      - ./.envs/.docker/.minio.env
    ports:
      - "8001:8000"
    command: /start

  postgres:
    image: docker.io/postgres:17
    container_name: sanaap_local_postgres
    volumes:
      - sanaap_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.docker/.postgres.env
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:6
    container_name: sanaap_local_redis
    volumes:
      - sanaap_local_redis_data:/data
    ports:
      - "6379:6379"

  minio:
    image: docker.io/minio/minio
    container_name: sanaap_local_minio
    volumes:
      - sanaap_local_minio_data:/data
    env_file:
      - ./.envs/.docker/.minio.env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  celeryworker:
    <<: *django
    image: sanaap_local_celery_worker
    container_name: sanaap_local_celery_worker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
