# === pytest ===
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=core.settings.test --reuse-db --import-mode=importlib"
python_files = [
    "tests.py",
    "test_*.py",
]

[tool.ruff]
extend-exclude = [
    "*/migrations/*.py",
    "staticfiles/*"
]

[tool.ruff.lint.isort]
force-single-line = true

[dependency-groups]
dev = [
    "django-extensions==4.1",
    "psycopg2-binary>=2.9.7",
    "pytest==8.4.2",
    "pytest-django==4.11.1",
    "pytest-sugar==1.1.1",
    "ruff==0.13.1",
]

[project]
name = "sanaap-backend-challenge-api"
version = "0.1.0"
description = "This project is interview project for sanaap"
readme = "README.md"

authors = [
    { name = "Hamzeh Pourmahdi", email="hpourmahdi@hotmail.com" },
]

requires-python = "==3.13.*"

dependencies = [
    "argon2-cffi==25.1.0",
    "boto3>=1.40.40",
    "celery==5.5.3",
    "django==5.2.6",
    "django-environ==0.12.0",
    "django-redis==6.0.0",
    "django-storages>=1.14.6",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "drf-spectacular==0.28.0",
    "pillow>=11.3.0",
    "psycopg===3.2.10",
    "redis==6.4.0",
]
