# Generated by Django 5.2.6 on 2025-09-25 19:57

from django.db import migrations

from django.contrib.auth.models import Group, Permission 

def create_groups_and_permissions(apps, schema_editor):
    # create groups
    admin_group, created = Group.objects.get_or_create(name='Admin')
    editor_group, created = Group.objects.get_or_create(name='Editor')
    viewer_group, created = Group.objects.get_or_create(name='Viewer')
    
    # assign permissions to groups
    all_permissions = Permission.objects.filter(content_type__model__in=["user", "group"])
    admin_group.permissions.set(all_permissions)

def reverse_groups_and_permissions(apps, schema_editor):
    Group.objects.filter(name__in=['Admin', 'Editor', 'Viewer']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'), 
        ('contenttypes', '0002_remove_content_type_name'), 
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, reverse_groups_and_permissions),
    ]
