# Generated by Django 5.2.6 on 2025-09-26 08:00

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def add_permissions_to_groups(apps, schema_editor):
    add_permission = Permission.objects.get(codename='add_document')
    change_permission = Permission.objects.get(codename='change_document')
    delete_permission = Permission.objects.get(codename='delete_document')
    view_permission = Permission.objects.get(codename='view_document')
    
    admin_group = Group.objects.get(name='Admin')
    editor_group = Group.objects.get(name='Editor')
    viewer_group = Group.objects.get(name='Viewer')
    
    admin_group.permissions.add(add_permission, change_permission, delete_permission, view_permission)
    editor_group.permissions.add(add_permission, change_permission, view_permission)
    viewer_group.permissions.add(view_permission)
    
def remove_permissions_from_groups(apps, schema_editor):
    permissions = Permission.objects.filter(codename__in=[
        'add_document', 'change_document', 'delete_document', 'view_document'
    ])
    
    admin_group = Group.objects.get(name='Admin')
    editor_group = Group.objects.get(name='Editor')
    viewer_group = Group.objects.get(name='Viewer')
    
    admin_group.permissions.remove(*permissions)
    editor_group.permissions.remove(*permissions)
    viewer_group.permissions.remove(*permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_permissions_to_groups, remove_permissions_from_groups),
    ]
